version: '3.4'
services:
  ollama:
    container_name: ollama
    image: ollama/ollama  # Replace with specific Ollama version if needed
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all  # Adjust count for the number of GPUs you want to use
    volumes:
      - ollama:/root/.ollama
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # file server

  postgresql:
    image: pgvector/pgvector:0.7.0-pg15
    shm_size: 2g
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Expose PostgreSQL default port
    networks:
      default:
        aliases:
          - postgresql

    volumes:
      - ./postgresql_data:/var/lib/postgresql/data  # Persistent data volume

  documentation:
    build:
      context: ./documentation
    ports:
      - "8004:3000"


  webapp:
    container_name: webapp
    depends_on:
      - postgresql
    build:
      context: ./webapp
      args:
        - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
        - DATABASE_URL=${DATABASE_URL}
        - OLLAMA_URL=${OLLAMA_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - AUTH_URL=${AUTH_URL}
        - NEXT_PUBLIC_S3_ACCESS_KEY=${S3_ACCESS_KEY}
        - NEXT_PUBLIC_S3_SECRET_KEY=${S3_SECRET_KEY}
        - NEXT_PUBLIC_S3_ENDPOINT=${S3_ENDPOINT}
        - NEXT_PUBLIC_S3_REGION=${S3_REGION}
        - NEXT_PUBLIC_S3_BUCKET=${S3_BUCKET}
        - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
        - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
        - S3_ACCESS_KEY=${S3_ACCESS_KEY}
        - S3_SECRET_KEY=${S3_SECRET_KEY}
        - S3_ENDPOINT=${S3_ENDPOINT}
        - S3_REGION=${S3_REGION}
        - S3_BUCKET=${S3_BUCKET}
        - SCW_ACCESS_KEY=${SCW_ACCESS_KEY}
        - SCW_SECRET_KEY=${SCW_SECRET_KEY}
        - SCW_PROJECT_ID=${SCW_PROJECT_ID}
        - SCW_REGION=${SCW_REGION}
        - H5P_URL=${H5P_URL}
        - H5P_PUBLIC_URL=${H5P_PUBLIC_URL}
        - MOODLE_NODE_SERVER_URL=${MOODLE_NODE_SERVER_URL}
        - MOODLE_URL=${MOODLE_URL}
        - MOODLE_TOKEN=${MOODLE_TOKEN}
        - GROQ_API_KEY=${GROQ_API_KEY}
        - ADA_H5P_SECRET=${ADA_H5P_SECRET}
        - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
        - H5P_JWT_SECRET=${H5P_JWT_SECRET}
        - SESSION_SECRET=${SESSION_SECRET}
        - GAR_CLIENT_ID=${GAR_CLIENT_ID}
        - GAR_CLIENT_SECRET=${GAR_CLIENT_SECRET}
        - GAR_ISSUER=${GAR_ISSUER}
        - GAR_ID_RESSOURCE=${GAR_ID_RESSOURCE}


    ports:
      - "8002:3000"
    environment:
      - NEXT_PUBLIC_S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - NEXT_PUBLIC_S3_SECRET_KEY=${S3_SECRET_KEY}
      - NEXT_PUBLIC_S3_ENDPOINT=${S3_ENDPOINT}
      - NEXT_PUBLIC_S3_REGION=${S3_REGION}
      - NEXT_PUBLIC_S3_BUCKET=${S3_BUCKET}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - DATABASE_URL=${DATABASE_URL}
      - OLLAMA_URL=${OLLAMA_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_URL=${AUTH_URL}
      - H5P_URL=${H5P_URL}
      - H5P_PUBLIC_URL=${H5P_PUBLIC_URL}
      - MOODLE_NODE_SERVER_URL=${MOODLE_NODE_SERVER_URL}
      - MOODLE_URL=${MOODLE_URL}
      - MOODLE_TOKEN=${MOODLE_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - H5P_JWT_SECRET=${H5P_JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - NEXT_PUBLIC_H5P_URL=${NEXT_PUBLIC_H5P_URL}
      - GAR_CLIENT_ID=${GAR_CLIENT_ID}
      - GAR_CLIENT_SECRET=${GAR_CLIENT_SECRET}
      - GAR_ISSUER=${GAR_ISSUER}
      - GAR_ID_RESSOURCE=${GAR_ID_RESSOURCE}
    healthcheck:
      test: ["CMD", "npx", "prisma", "db", "push"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    runtime: nvidia
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - YOUTUBE_PROXY=${YOUTUBE_PROXY}
      - YOUTUBE_TOKEN_GENERATOR_URL=${YOUTUBE_TOKEN_GENERATOR_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./documents:/server/documents
      - ./ftp-data:/server/ftp-data

  h5p:
    container_name: h5p
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - WEBAPP_URL=${WEBAPP_URL}
      - ADA_H5P_SECRET=${ADA_H5P_SECRET}
      - WEBAPP_URL=${WEBAPP_URL}
      - H5P_JWT_SECRET=${H5P_JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - NEXT_PUBLIC_H5P_URL=${NEXT_PUBLIC_H5P_URL}
    build:
      context: ./h5p
    ports:
      - "8006:8006"
      # - "127.0.0.1:8006:8006"
    restart: always
    volumes:
      - ./h5p:/app/h5p
      - ./public:/app/public

  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    build: moodle
    container_name: moodle
    ports:
      - '127.0.0.1:8008:8080'
      - '127.0.0.1:8022:22'
      - '127.0.0.1:8009:3000'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'

  youtube-token-generator:
    image: quay.io/invidious/youtube-trusted-session-generator:webserver
    ports:
      - "8007:8080"
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/moodle/data/mariadb
  moodle_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/moodle/data/moodle
  moodledata_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/moodle/data/moodledata
  ollama:
    driver: local