version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.25.4
    restart: on-failure:0
    ports:
    - 8080:8080
    - 50051:50051
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-custom:8080
      CLUSTER_HOSTNAME: 'node1'

  # TODO just to test, later change to https://huggingface.co/OrdalieTech/Solon-embeddings-base-0.1 
  t2v-custom:
    runtime: nvidia
    image: solon-inference
    environment:
      ENABLE_CUDA: 0

  weaviate-console:
    container_name: weaviate_console
    image: semitechnologies/weaviate-console:latest
    ports:
      - 4242:80

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # file server
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./documents:/usr/share/nginx/html/documents

  webapp:
    build:
      context: ./webapp
      args:
        - NEXT_PUBLIC_FILE_SERVER_URL=${NEXT_PUBLIC_FILE_SERVER_URL}
        - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
    ports:
      - "8002:3000"
  
  server:
    runtime: nvidia
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=${WEAVIATE_URL}
      - WEAVIATE_PORT=${WEAVIATE_PORT}
      - WEAVIATE_GRPC_PORT=${WEAVIATE_GRPC_PORT}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./documents:/server/documents
      - ./ftp-data:/server/ftp-data

  # automatically index files when upoaded to ftp
  ftp_processing:
    runtime: nvidia
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=${WEAVIATE_URL}
      - WEAVIATE_PORT=${WEAVIATE_PORT}
      - WEAVIATE_GRPC_PORT=${WEAVIATE_GRPC_PORT}
    build:
      context: ./server
    volumes:
      - ./documents:/server/documents
      - ./ftp-data:/server/ftp-data
    command: ["python", "app/processing.py"]

  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd
    ports:
      - "8003:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./ftp-data:/home/ftpuser"
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      - FTP_USER_NAME=scienceinfuse
      - FTP_USER_PASS=${FTP_PASSWORD}
      - FTP_USER_HOME=/home/ftpuser
      - PUBLICHOST=${SERVER_IP}
      - PURE_FTPD_FLAGS=--tls=2
    restart: always