version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    image: docker.io/bitnami/moodle:4.5
    ports:
      - '8081:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      # - './plugins:/tmp/plugins'
      # - './install-plugins.sh:/docker-entrypoint-init.d/install-plugins.sh'
      # - './fix-permissions.sh:/docker-entrypoint-init.d/fix-permissions.sh'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/mariadb
  moodle_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/moodle
  moodledata_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/moodledata