// 'use client';
// // import H5PRenderer from "@/app/mediaViewers/H5PRenderer";
// // import { H5PPlayerUI } from "@lumieducation/h5p-react";

// import { ContentService } from "@/lib/h5p/services/ContentService";
// import { H5PPlayerUI } from "@lumieducation/h5p-react";


// const contentService = new ContentService(process.env.NEXT_PUBLIC_H5P_URL || "");


// export default function H5pEmbedPage({ params }: { params: { contentId: string } }) {
//     return (
//         <H5PPlayerUI
//             contentId={params.contentId}
//             loadContentCallback={contentService.getPlay}
//         />
//         // <H5PRenderer
//         //     h5pContentId={'3591175282'}
//         // />
//     );
// }



// app/(embed)/embed/h5p/[contentId]/page.tsx
// This path will now resolve to yoursite.com/embed/h5p/some-id

// Optional: Add metadata if needed
export async function generateMetadata({ params }: { params: { contentId: string } }) {
    return {
      title: `Embedded H5P ${params.contentId}`,
      // Prevent indexing if this is purely embedded content
      robots: { index: false, follow: false },
    };
  }
  
  export default function EmbedH5PPage({ params }: { params: { contentId: string } }) {
    // This content is rendered inside app/(embed)/layout.tsx,
    // which itself is technically inside the <body> tag generated by the
    // root app/layout.tsx, but the root layout's direct children
    // (DSFRProvider, Header, Footer, etc.) are NOT rendered around this.
    return (
      <>
        <h1>I love cats (Content ID: {params.contentId})</h1>
        {/* Your H5P rendering logic here */}
      </>
    );
  }